import { createFileRoute } from "@tanstack/react-router";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";
import { EmptyState, GlassCard, PageHeader, PriorityBadge, SectionTitle } from "@/components/warehouse/Primitives";
import { useWarehouse } from "@/state/warehouse-store";
import { buildAllocationPlans } from "@/lib/warehouse-logic";

export const Route = createFileRoute("/allocation")({
  head: () => ({
    meta: [
      { title: "Smart Allocation — WareMind" },
      { name: "description", content: "Priority-weighted stock allocation plans with partial fulfilment and shortfall handling." },
      { property: "og:title", content: "Smart Allocation — WareMind" },
      { property: "og:description", content: "Priority-weighted stock allocation plans generated by the decision engine." },
    ],
  }),
  component: AllocationPage,
});

function AllocationPage() {
  const { products, orders, allocate } = useWarehouse();
  const plans = buildAllocationPlans(products, orders);
  const actionable = plans.filter((p) => p.allocate > 0);

  return (
    <div>
      <PageHeader
        title="Smart Allocation Engine"
        description="Stock is committed to the highest-priority outstanding demand first. Shortfalls stay pending and trigger replenishment."
        action={
          actionable.length ? (
            <button
              onClick={() => {
                actionable.forEach((p) => allocate(p.orderId, p.productId, p.allocate));
                toast.success("Allocation plan executed", {
                  description: `${actionable.length} line(s) committed by priority weighting.`,
                });
              }}
              className="rounded-xl bg-gradient-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5"
            >
              Run full allocation
            </button>
          ) : undefined
        }
      />

      <GlassCard className="p-5">
        <SectionTitle title="Generated plan" subtitle={`${plans.length} outstanding demand line(s)`} icon={<Sparkles className="size-5" />} />
        {plans.length === 0 ? (
          <EmptyState title="Every order line is fully allocated" hint="The engine has nothing left to commit." />
        ) : (
          <div className="space-y-3">
            {plans.map((p) => (
              <div key={`${p.orderId}-${p.productId}`} className="rounded-2xl border border-border/70 bg-secondary/35 p-4">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-mono text-sm">{p.orderId}</span>
                  <span className="font-medium">{p.productName}</span>
                  <PriorityBadge priority={p.priority} />
                </div>
                <div className="mt-3 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4">
                  <div><p className="text-muted-foreground">Requested</p><p className="font-medium">{p.requested}</p></div>
                  <div><p className="text-muted-foreground">Available</p><p className="font-medium">{p.availableNow}</p></div>
                  <div><p className="text-muted-foreground">Allocate</p><p className="font-medium text-success">{p.allocate}</p></div>
                  <div><p className="text-muted-foreground">Shortfall</p><p className="font-medium text-warning">{p.shortfall}</p></div>
                </div>
                <div className="mt-3 flex flex-wrap items-center justify-between gap-2">
                  <p className="text-xs text-muted-foreground">
                    {p.shortfall > 0
                      ? `Partial fulfilment protects the deadline; ${p.shortfall} unit(s) pending replenishment.`
                      : "Free stock covers the full outstanding quantity."}
                  </p>
                  <button
                    disabled={p.allocate <= 0}
                    onClick={() => {
                      allocate(p.orderId, p.productId, p.allocate);
                      toast.success(`Allocated ${p.allocate} × ${p.productName}`, { description: `Committed to ${p.orderId}.` });
                    }}
                    className="rounded-lg bg-gradient-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:opacity-40"
                  >
                    {p.allocate > 0 ? `Allocate ${p.allocate}` : "No stock available"}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </GlassCard>
    </div>
  );
}
